name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  secrets: read

env:
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: [uses: fastai/workflows/quarto-ghp@master]
